Feat/tela despesas
ByteCarlos/custo-facil-web pull request #2
Opened 2024-10-13 01:10 UTC by DeeStuani

Esta feature envolve a criação inicial e preparação para a estilização da tela de despesas. As seguintes alterações foram realizadas:

Criação da estrutura básica da tela de despesas.
Implementação inicial de componentes principais da tela, como a listagem de despesas e o formulário de adição de nova despesa.
Organização dos arquivos de estilo para facilitar a futura estilização (CSS ou styled-components, dependendo do projeto).
Adição de classes e IDs nos elementos HTML para permitir a estilização mais refinada posteriormente.
Configuração dos estados iniciais dos componentes (se houver controle de estado).
Próximos Passos:
Ajustes e refinamentos de estilo conforme o design final.
Implementação de funcionalidades adicionais, como filtros e ordenação das despesas.

2024-10-14 00:48 UTC, ByteCarlos requested changes
Por favor, verifique as alterações solicitadas.

2024-10-14 00:48 UTC, ByteCarlos commented on src/pages/despesas/Despesas.css
> +.content-container {
o estilo da classe content-container não pode ser alterada em um componente!

2024-10-14 00:48 UTC, ByteCarlos commented on src/pages/despesas/Despesas.css
> +.form-group button {
lembre-se de utilizar a classe pai do componente que você definiu `despesas-container`, segue um exemplo de como fazer com o seletor de aninhamento & :
```
.despesas-container {
  /* parent rule style properties */
  & .form-group button {
    /* child rule style properties */
  }
  
  & .form-group.d-flex{
    /* child rule style properties */
  }
}
```
Segue o link para ver mais exemplos e explicação sobre u

2024-10-14 00:48 UTC, ByteCarlos commented on src/pages/despesas/Despesas.tsx
> +  const calculateDaysLeft = (endDate: string) => {
esse tipo de função você pode separar em um arquivo .ts, crie um pasta utils dentro da pasta src do projeto e crie um arquivo `calculateDaysLeft.ts` dentro exportando essa função. Depois importe ela dentro do seu componente para usar.

2024-10-14 00:48 UTC, ByteCarlos commented on src/pages/despesas/Despesas.tsx
> +  }, []);
o `useEffect` precisa de uma dependencia dentro do segundo parametro `[ ]`, para garantir que não seja ativada a todo momento.
Leia: [https://pt-br.legacy.reactjs.org/docs/hooks-effect.html](url)

2024-10-16 00:54 UTC, DeeStuani commented on src/pages/despesas/Despesas.css
> +.form-group button {
Implementado

2024-10-16 01:01 UTC, DeeStuani commented on src/pages/despesas/Despesas.tsx
> +  }, []);
resolvido adicionado o daysLeft

2024-10-16 02:35 UTC, DeeStuani commented on src/pages/despesas/Despesas.css
> +.content-container {
resolvido

2024-10-16 02:40 UTC, DeeStuani commented on src/pages/despesas/Despesas.tsx
> +  const calculateDaysLeft = (endDate: string) => {
feito

2024-10-16 04:21 UTC, ByteCarlos approved these changes
Aprovado!

2024-10-16 04:21 UTC, merged